# Generated by Django 5.0.7 on 2024-07-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='institucion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
