# Generated by Django 5.0.7 on 2024-07-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0002_formacion_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='egreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
