# Generated by Django 5.0.7 on 2024-07-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0003_alter_formacion_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='egreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
