# Generated by Django 5.0.7 on 2024-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('image', models.ImageField(upload_to='', verbose_name='imagen')),
                ('link', models.URLField(max_length=180, verbose_name='enlace')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
