# Generated by Django 5.0.7 on 2024-07-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='proyectos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=180, null=True, verbose_name='enlace'),
        ),
    ]
