# Generated by Django 5.0.7 on 2024-07-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioApp', '0002_alter_project_options_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=180, null=True, verbose_name='enlace'),
        ),
    ]
